blackduck:
  url: 'https://seangpost.app.blackduck.com/'
  trust.cert: true
  api.token: 'ODAyYjdjMGMtZTNiNy00ZTc0LWIwNGUtZWQ4YWY3NDdmMTFkOjY4ZWQzMjEzLWZjNDItNDQ5Zi1hMzZmLWU5YTBjNWExMjExZA=='
detect:
  project.name: 'azure-devops-yml'
  project.version.name: '1'
  blackduck.signature.scanner.exclusion.patterns: '/*/bin/,/*/obj/,/packages/'
  detector.search.depth: 1
